openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/logging/verbosityByName:
    post:
      operationId: verbosityByName
      summary: "[Logging] debug_verbosityByName"
      description: |
        Sets the verbosity of log module with given name. Please note that VerbosityByName only works with zapLogger.

        (Level : 0=crit, 1=error, 2=warn, 3=info, 4=debug, 5=trace)

        The verbosity of individual packages and source files can be raised using debug_vmodule.
        
        **JSONRPC:** `debug_verbosityByName`

      tags:
        - debug

      parameters:
        - name: name 
          in: query
          description: The module name.
          required: true 
          schema: 
            type: string
        - name: level
          in: query
          description: The logging verbosity level.
          required: true
          schema:
            type: integer

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/VerbosityByNameReq"

      responses:
        200:
          description: Return value null.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/VerbosityByNameResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/logging/verbosityByName.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/logging/DebugVerbosityByNameExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/debug/logging/verbosityByName.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/logging/verbosityByName.py"

components:
  schemas:
    VerbosityByNameReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'debug_verbosityByName'
        params: 
          items: 
            anyOf:
              - title: Name 
                description: The module name.
                type: string
              - title: Level
                description: The logging verbosity level.
                type: integer
          example: ["API", 1] 

    VerbosityByNameResp:
      type: object
      properties:
        result:
            type: string
            example: null