openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/logging/vmodule:
    post:
      operationId: vmodule
      summary: "[Logging] debug_vmodule"
      description: |
        Sets the logging verbosity pattern.
        
        **JSONRPC:** `debug_vmodule`

      tags:
        - debug

      parameters:
        - name: module
          in: query
          description: The module name for logging.
          required: true 
          schema: 
            type: string
       
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/VmoduleReq"

      responses:
        200:
          description: Return value null.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/VmoduleResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/logging/vmodule.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/logging/DebugVModuleExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/debug/logging/vmodule.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/logging/vmodule.py"

components:
  schemas:
    VmoduleReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'debug_vmodule'
        params: 
          description: The module name for logging.
          items:
            title: Module
            type: string
          example: ["p2p=4"]

    VmoduleResp:
      type: object
      properties:
        result:
            type: string
            example: null