openapi: "3.0.2"
info:
  title: KAIA Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /mainbridge/getChildChainIndexingEnabled:
    post:
      summary: "mainbridge_getChildChainIndexingEnabled"
      tags:
        - mainbridge
      operationId: getChildChainIndexingEnabled
      description: |
        mainbridge_getChildChainIndexingEnabled returns if indexing anchoring transaction is enabled or not.

        **JSONRPC:** `mainbridge_getChildChainIndexingEnabled`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/MainbridgeGetChildChainIndexingEnabledReq"

      responses:
        200:
          description: mainbridge_getChildChainIndexingEnabled returns if indexing anchoring transaction is enabled or not.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/MainbridgeGetChildChainIndexingEnabledResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/mainbridge/getChildChainIndexingEnabled.sh"
        # - lang: "Java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "JavaScript"
        #   label: "Javascript"
        #   source:
        #     $ref: ""
        # - lang: "Python"
        #   label: "Python"
        #   source:
        #     $ref: ""

components:
  schemas:
    MainbridgeGetChildChainIndexingEnabledReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'mainbridge_getChildChainIndexingEnabled'

    MainbridgeGetChildChainIndexingEnabledResp:
      type: object
      properties:
        result:
          type: boolean
          description: true if the indexing was enabled, false otherwise.
          example: true