openapi: "3.0.2"
info:
  title: KLAYTN OPEN API
  version: "1.10.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: mainbridge
    description: API for mainbridge namespace
servers:
  - url: http://localhost:7151
  - url: https://public-en-kairos.node.kaia.io
  - url: https://public-en.node.kaia.io
paths:
  # mainbridge:
  /mainbridge/getChildChainIndexingEnabled:
    $ref: ./getChildChainIndexingEnabled.yaml#/paths/~1mainbridge~1getChildChainIndexingEnabled
  /mainbridge/nodeInfo:
    $ref: ./nodeInfo.yaml#/paths/~1mainbridge~1nodeInfo
  /mainbridge/convertChildChainBlockHashToParentChainTxHash:
    $ref: ./convertChildChainBlockHashToParentChainTxHash.yaml#/paths/~1mainbridge~1convertChildChainBlockHashToParentChainTxHash
  /mainbridge/addPeer:
    $ref: ./addPeer.yaml#/paths/~1mainbridge~1addPeer
  /mainbridge/removePeer:
    $ref: ./removePeer.yaml#/paths/~1mainbridge~1removePeer