openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /personal/lockAccount:
    post:
      operationId: lockAccount
      summary: "personal_lockAccount"
      description: |
        Removes the private key with a given address from memory. The account can no longer be used to send transactions.

        **JSONRPC:** `personal_lockAccount`
      tags:
        - personal

      parameters:
        - name: address
          required: true
          schema:
            type: string
          description: The account address to lock.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: "personal_lockAccount"
                    params:
                      type: array
                      items:
                        title: address
                        type: string
                      description: "The account address to lock."
                      example: ["0xfa415bb3e6231f488ff39eb2897db0ef3636dd32"]

      responses:
        200:
          description: Return the locked status of the account.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: boolean
                        description: true if the account was successfully locked, false otherwise.
                        example: true

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/personal/lockAccount.sh"
        - lang: "Java"
          label: "Java"
          source:
             $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/personal/PersonalLockAccountExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/personal/lockAccount.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/personal/lockAccount.py"
