openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /personal/sign:
    post:
      operationId: sign
      summary: "personal_sign"
      description: |
        The method calculates an [EIP-191](https://eips.ethereum.org/EIPS/eip-191) signature: ```sign(keccak256("\x19Ethereum Signed Message:\n" + len(message) + message)))```

        **NOTE**: In versions earlier than Kaia v1.0.1, the method calculates an [KIP-97](https://kips.kaia.io/KIPs/kip-97) signature: sign(keccak256("\x19Klaytn Signed Message:\n" + len(message) + message)))

        The personal_ecRecover and kaia_recoverFromMessage methods can verify the signature.

        **JSONRPC:** `personal_sign`
      tags:
        - personal

      parameters:
        - name: message
          required: true
          schema:
            type: string
          description: A message to sign.
          in: query
        - name: account
          required: true
          schema:
            type: string
          description: The account address.
          in: query
        - name: password
          required: true
          schema:
            type: string
          description: The pass phrase used for signing.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/PersonalSignReq"

      responses:
        200:
          description: Return the a signature.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        description: A signature.
                        example: "0xa3f20717a250c2b0b729b7e5becbff67fdaef7e0699da4de7ca5895b02a170a12d887fd3b17bfdce3481f10bea41f45ba9f709d39ce8325427b57afcfc994cee1b"
      
      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/personal/sign.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/personal/PersonalSignExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/personal/sign.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/personal/sign.py"

components:
  schemas:
    PersonalSignReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'personal_sign'
        params:
          type: array
          items:
            properties:
              Message:
                type: string
                title: Message
                description: A message to sign.
              Account:
                type: string
                title: Account
                description: The account address.
              Password:
                type: string
                title: Password
                description: The pass phrase used for signing.
          example: ["0xdead", "0x9b2055d370f73ec7d8a03e965129118dc8f5bf83", "gr8=B!0@uc$b"]

