openapi: "3.0.2"
info:
  title: KAIA Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/account/accounts:
    post:
      summary: "[Account] eth_accounts"
      tags:
        - eth
      operationId: accounts
      description: |
        Returns a list of addresses owned by client
        
        **JSONRPC:** `eth_accounts`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: eth_accounts

      responses:
        200:
          description: Addresses owned by the client
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthAccountsResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/account/accounts.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/account/EthAccountsExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/account/accounts.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/eth/account/accounts.py"

components:
  schemas:
    EthAccountsResp:
      type: object
      properties:
        result:
          type: array
          description: Addresses owned by the client.
          items:
            type: string
            format: 20-byte DATA
            readOnly: true
            example: "0xc94770007dda54cF92009BFF0dE90c06F603a09f"
