openapi: "3.0.2"
info:
  title: KAIA Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/account/sign:
    post:
      summary: "[Account] eth_sign"
      tags:
        - eth
      operationId: sign
      description: |
        The method calculates an [EIP-191](https://eips.ethereum.org/EIPS/eip-191) signature: ```sign(keccak256("\x19Ethereum Signed Message:\n" + len(message) + message)))```

        **NOTE**: In versions earlier than Kaia v1.0.1, the method calculates an [KIP-97](https://kips.kaia.io/KIPs/kip-97) signature: sign(keccak256("\x19Klaytn Signed Message:\n" + len(message) + message)))

        The personal_ecRecover and kaia_recoverFromMessage methods can verify the signature.

        **JSONRPC:** `eth_sign`

      parameters:
        - name: account
          in: query
          description: Address
          required: true
          schema:
            type: string
            format: 20-byte DATA
        - name: message
          in: query
          description: Message to sign
          required: true
          schema:
            type: string
            format: N-byte DATA

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: eth_sign
                    params:
                      type: array
                      items:
                        anyOf:
                          - title: Account
                            description: Address
                            type: string
                            format: 20-byte DATA
                          - title: Message
                            description: Message to sign
                            type: string
                            format: N-byte DATA
                      example: ["0x9b2055d370f73ec7d8a03e965129118dc8f5bf83", "0xdeadbeaf"]

      responses:
        200:
          description: Return signature
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: DATA
                        description: Signature
                        example: "0xa3f20717a250c2b0b729b7e5becbff67fdaef7e0699da4de7ca5895b02a170a12d887fd3b17bfdce3481f10bea41f45ba9f709d39ce8325427b57afcfc994cee1b"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/account/sign.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/account/EthSignExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/account/sign.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/eth/account/sign.py"
