openapi: "3.0.2"
info:
  title: KAIA Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/profiling/stopCPUProfile:
    post:
      summary: "[Profiling] debug_stopCPUProfile"
      tags:
        - debug
      operationId: stopCPUProfile
      description: |
        Turns off CPU profiling.

        **JSONRPC:** `debug_stopCPUProfile`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/DebugStopCPUProfileReq"

      responses:
        200:
          description: Turns off CPU profiling.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/DebugStopCPUProfileResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/profiling/stopCPUProfile.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/profiling/DebugStopCPUProfileExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/debug/profilling/stopCPUProfile.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/profiling/stopCPUProfile.py"

components:
  schemas:
    DebugStopCPUProfileReq:
      type: object
      properties:
        method:
          type: string
          default: debug_stopCPUProfile

    DebugStopCPUProfileResp:
      type: object
      properties:
        result:
          type: string
          nullable: true
          default: null
