openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /kaia/configuration/gasPrice:
    post:
      operationId: .gasPrice
      summary: "[Configuration] kaia_gasPrice"
      description: |
        Returns a recommended gasPrice for a new transaction.

        - Before Magma, returns the fixed UnitPrice
        - After Magma, returns the twice of next baseFee (2*baseFee)
        - After Kaia, returns slightly buffered baseFee plus recommended tip (BaseFee * (1.10 or 1.15) + eth_maxPriorityFeePerGas)
                
        **JSONRPC:** `kaia_gasPrice`
      tags:
        - kaia

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: kaia_gasPrice

      responses:
        200:
          description: Recommended gas price in kei.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: hex
                        description: Recommended gas price in kei.
                        example: "0xAE9F7BCC00"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/kaia/configuration/gasPrice.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/kaia/configuration/KaiaGasPriceExample.java"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/kaia/configuration/gasPrice.py"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/kaia/configuration/gasPrice.js"

