openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  contact:
    name: API support
    url: https://devforum.kaia.io/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: txpool
    description: API for txpool namespace
servers:
  - url: http://localhost:7151
  - url: https://public-en-kairos.node.kaia.io
  - url: https://public-en.node.kaia.io
paths:
  # txpool
  /txpool/status:
    $ref: ./status.yaml#/paths/~1txpool~1status
  /txpool/content:
    $ref: ./content.yaml#/paths/~1txpool~1content
  /txpool/inspect:
    $ref: ./inspect.yaml#/paths/~1txpool~1inspect
