openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/account/getAccountKey:
    post:
      operationId: getAccountKey
      summary: "[Account] klay_getAccountKey"
      description: |
        Returns the account key of the Externally Owned Account (EOA) of a given address. If the account has AccountKeyLegacy or the account of the given address is a Smart Contract Account, it will return an empty key value.

        **NOTE:** *In versions earlier than Kaia v1.7.0, only integer block number, the string "earliest" and "latest" are available*

        **JSONRPC:** `klay_getAccountKey`
      tags:
        - klay

      parameters:
        - name: address
          required: true
          schema:
            type: string
            format: 20-byte DATA
          description: Address
          in: query
        - name: blockNumberOrHashOrTag
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter, or block hash.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayGetAccountKeyReq"

      responses:
        200:
          description: Returns the account key or an empty key value.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayGetAccountKeyResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/account/getAccountKey.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/account/KlayGetAccountKeyExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/account/getAccountKey.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/account/getAccountKey.py"

components:
  schemas:
    KlayGetAccountKeyReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_getAccountKey'
        params:
          type: array
          items:
            properties:
              Address:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/Address"
              BlockNumberOrHashOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"
          example:  ["0x3111a0577f322e8fb54f78d9982a26ae7ca0f722", "latest"]

    KlayGetAccountKeyResp:
      type: object
      properties:
        result:
          oneOf:
              - $ref: "#/components/schemas/AccountKeyLegacy"
              - $ref: "#/components/schemas/AccountKeyNil"
              - $ref: "#/components/schemas/AccountKeyPublic"
              - $ref: "#/components/schemas/AccountKeyFail"
              - $ref: "#/components/schemas/AccountKeyWeightedMultiSig"
              - $ref: "#/components/schemas/AccountKeyRoleBased"

          example:
            {
              key: {
                x: "0x230037a99462acd829f317d0ce5c8e2321ac2951de1c1b1a18f9af5cff66f0d7",
                y: "0x18a7fb1b9012d2ac87bc291cbf1b3b2339356f1ce7669ae68405389be7f8b3b6"
              },
              keyType: 2
            }

    AccountKeyNil:
      title: AccountKeyNil
      type: string

    AccountKeyLegacy:
      title: AccountKeyLegacy
      type: object
      required:
        - key
        - keyType
      description: "AccountKeyLegacy is used for the account having an address derived from the corresponding key pair"
      properties:
        key:
          type: object
        keyType:
          type: integer
          description: "The type of AccountKeyLegacy. This must be 0x01."

    AccountKeyPublic:
      title: AccountKeyPublic
      type: object
      required:
        - key
        - keyType
      description: "AccountKeyPublic is used for accounts having one public key."
      properties:
        key:
          type: object
          required:
            - x
            - y
          description: "Key should be a compressed public key on S256 curve."
          properties:
            x:
              type: string
              format: 32-byte DATA
              description: "The x coordinate of the public key."
            y:
              type: string
              format: 32-byte DATA
              description: "The y coordinate of the public key."
        keyType:
          type: integer
          description: "The type of AccountKeyPublic. This must be 0x02."

    AccountKeyFail:
        title: AccountKeyFail
        type: object
        required:
          - keyType
          - key
        description: "If an account has the key AccountKeyFail, the transaction validation process always fails. It can be used for smart contract accounts so that a transaction sent from the smart contract account always fails."
        properties:
            key:
              type: object
            keyType:
              type: integer
              description: "The type of AccountKeyFail. This must be 0x03."

    AccountKeyWeightedMultiSig:
      title: AccountKeyWeightedMultiSig
      type: object
      required:
        - keyType
        - Threshold
        - WeightedPublicKeys
      description: "AccountKeyWeightedMultiSig is an account key type containing a threshold and WeightedPublicKeys which contains a list consisting of a public key and its weight."
      properties:
        keyType:
          type: integer
          description: "The type of AccountKeyWeightedMultiSig. This must be 0x04."
        Threshold:
          type: integer
          description: "Validation threshold. To be a valid transaction, the weight sum of signatures should be larger than or equal to the threshold."
        WeightedPublicKeys:
            type: array
            description: "A list of weighted public keys. A weighted public key contains a compressed public key and its weight."
            items:
                type: object
                required:
                  - PublicKey
                  - Weight
                properties:
                  PublicKey:
                      type: object
                      required:
                          - x
                          - y
                      properties:
                        x:
                            type: string
                            format: 32-byte DATA
                            description: "The x coordinate of the public key."
                        y:
                            type: string
                            format: 32-byte DATA
                            description: "The y coordinate of the public key."
                  Weight:
                      type: integer

    AccountKeyRoleBased:
      title: AccountKeyRoleBased
      type: object
      required:
          - keyType
          - key
      description: "AccountKeyRoleBased represents a role-based key"
      properties:
        key:
          type: array
          description: "A list of keys. A key can be any of AccountKeyNil, AccountKeyLegacy, AccountKeyPublic, AccountKeyFail, and AccountKeyWeightedMultiSig"
          items:
            anyOf:
              - $ref: "#/components/schemas/AccountKeyNil"
              - $ref: "#/components/schemas/AccountKeyLegacy"
              - $ref: "#/components/schemas/AccountKeyPublic"
              - $ref: "#/components/schemas/AccountKeyFail"
              - $ref: "#/components/schemas/AccountKeyWeightedMultiSig"
        keyType:
          type: integer
          description: "The type of AccountKeyRoleBased. This must be 0x05."
