generatorName: web3rpc-javascript
outputDir: ./openapi
inputSpec: ../../../rpc-specs/namespaces/all-except-eth.yaml
projectName: "@kaiachain/web3rpc"
projectVersion: "1.2.0"
templateDir: ./template
sortParamsByRequiredFlag: false
globalProperties:
  apiDocs: false
  modelDocs: false
  modelTests: false
  apiTests: false
  # only generate apis, skip models.
  supportingFiles: ''
  apis: ''
inlineSchemaNameMappings:
  accountCreated_default_response: AccountCreatedResponse
  getRewards_default_response: GetRewardsResponse
  ethAccounts_default_response: EthAccountsDefaultResponse
  ethBlockNumber_default_response: EthBlockNumberDefaultResponse
  ethCall_default_response: EthCallDefaultResponse
