openapi: "3.0.2"
info:
  title: web3rpc
  version: "0.9.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
x-tagGroups:
  - name: namespaces
    tags:
      - debug
servers:
  - url: https://public-en-kairos.node.kaia.io
  - url: https://public-en.node.kaia.io
  - url: https://localhost:8551
paths:
   # debug/logging:
  /debug/logging/setVMLogTarget:
    $ref: ../../web3rpc/rpc-specs/paths/debug/logging/setVMLogTarget.yaml#/paths/~1debug~1logging~1setVMLogTarget
  /debug/logging/verbosity:
    $ref: ../../web3rpc/rpc-specs/paths/debug/logging/verbosity.yaml#/paths/~1debug~1logging~1verbosity
  /debug/logging/verbosityByName:
    $ref: ../../web3rpc/rpc-specs/paths/debug/logging/verbosityByName.yaml#/paths/~1debug~1logging~1verbosityByName
  /debug/logging/verbosityByID:
    $ref: ../../web3rpc/rpc-specs/paths/debug/logging/verbosityByID.yaml#/paths/~1debug~1logging~1verbosityByID
  /debug/logging/vmodule:
    $ref: ../../web3rpc/rpc-specs/paths/debug/logging/vmodule.yaml#/paths/~1debug~1logging~1vmodule
  /debug/logging/backtraceAt:
    $ref: ../../web3rpc/rpc-specs/paths/debug/logging/backtraceAt.yaml#/paths/~1debug~1logging~1backtraceAt

  # debug/blockchainInspection:
  /debug/blockchainInspection/preimage:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/preimage.yaml#/paths/~1debug~1blockchainInspection~1preimage
  /debug/blockchainInspection/dumpBlock:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/dumpBlock.yaml#/paths/~1debug~1blockchainInspection~1dumpBlock
  /debug/blockchainInspection/dumpStateTrie:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/dumpStateTrie.yaml#/paths/~1debug~1blockchainInspection~1dumpStateTrie
  /debug/blockchainInspection/getBlockRlp:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/getBlockRlp.yaml#/paths/~1debug~1blockchainInspection~1getBlockRlp
  /debug/blockchainInspection/getModifiedAccountsByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/getModifiedAccountsByNumber.yaml#/paths/~1debug~1blockchainInspection~1getModifiedAccountsByNumber
  /debug/blockchainInspection/getModifiedAccountsByHash:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/getModifiedAccountsByHash.yaml#/paths/~1debug~1blockchainInspection~1getModifiedAccountsByHash
  /debug/blockchainInspection/getBadBlocks:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/getBadBlocks.yaml#/paths/~1debug~1blockchainInspection~1getBadBlocks
  /debug/blockchainInspection/printBlock:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/printBlock.yaml#/paths/~1debug~1blockchainInspection~1printBlock
  /debug/blockchainInspection/setHead:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/setHead.yaml#/paths/~1debug~1blockchainInspection~1setHead
  /debug/blockchainInspection/startWarmUp:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/startWarmUp.yaml#/paths/~1debug~1blockchainInspection~1startWarmUp
  /debug/blockchainInspection/startContractWarmUp:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/startContractWarmUp.yaml#/paths/~1debug~1blockchainInspection~1startContractWarmUp
  /debug/blockchainInspection/stopWarmUp:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/stopWarmUp.yaml#/paths/~1debug~1blockchainInspection~1stopWarmUp
  /debug/blockchainInspection/startCollectingTrieStats:
    $ref: ../../web3rpc/rpc-specs/paths/debug/blockchainInspection/startCollectingTrieStats.yaml#/paths/~1debug~1blockchainInspection~1startCollectingTrieStats

  #debug/others
  /debug/others/getModifiedStorageNodesByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/debug/others/getModifiedStorageNodesByNumber.yaml#/paths/~1debug~1others~1getModifiedStorageNodesByNumber
  /debug/others/chaindbCompact:
    $ref: ../../web3rpc/rpc-specs/paths/debug/others/chaindbCompact.yaml#/paths/~1debug~1others~1chaindbCompact
  /debug/others/chaindbProperty:
    $ref: ../../web3rpc/rpc-specs/paths/debug/others/chaindbProperty.yaml#/paths/~1debug~1others~1chaindbProperty
  /debug/others/storageRangeAt:
    $ref: ../../web3rpc/rpc-specs/paths/debug/others/storageRangeAt.yaml#/paths/~1debug~1others~1storageRangeAt
  /debug/others/seedHash:
    $ref: ../../web3rpc/rpc-specs/paths/debug/others/seedHash.yaml#/paths/~1debug~1others~1seedHash
  /debug/others/setMutexProfileFraction:
    $ref: ../../web3rpc/rpc-specs/paths/debug/others/setMutexProfileFraction.yaml#/paths/~1debug~1others~1setMutexProfileFraction

  # debug/vMTracing:
  /debug/vMTracing/traceTransaction:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMTracing/traceTransaction.yaml#/paths/~1debug~1vMTracing~1traceTransaction
  /debug/vMTracing/traceBlockByHash:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMTracing/traceBlockByHash.yaml#/paths/~1debug~1vMTracing~1traceBlockByHash
  /debug/vMTracing/traceBlockByNumberRange:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMTracing/traceBlockByNumberRange.yaml#/paths/~1debug~1vMTracing~1traceBlockByNumberRange
  /debug/vMTracing/traceBlockByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMTracing/traceBlockByNumber.yaml#/paths/~1debug~1vMTracing~1traceBlockByNumber
  /debug/vMTracing/traceBlockFromFile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMTracing/traceBlockFromFile.yaml#/paths/~1debug~1vMTracing~1traceBlockFromFile
  /debug/vMTracing/traceBadBlock:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMTracing/traceBadBlock.yaml#/paths/~1debug~1vMTracing~1traceBadBlock
  /debug/vMTracing/traceBlock:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMTracing/traceBlock.yaml#/paths/~1debug~1vMTracing~1traceBlock
  /debug/vMTracing/traceChain:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMTracing/traceChain.yaml#/paths/~1debug~1vMTracing~1traceChain
  /debug/vMTracing/traceCall:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMTracing/traceCall.yaml#/paths/~1debug~1vMTracing~1traceCall

  # debug/vMStandardTracing:
  /debug/vMStandardTracing/standardTraceBlockToFile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMStandardTracing/standardTraceBlockToFile.yaml#/paths/~1debug~1vMStandardTracing~1standardTraceBlockToFile
  /debug/vMStandardTracing/standardTraceBadBlockToFile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/vMStandardTracing/standardTraceBadBlockToFile.yaml#/paths/~1debug~1vMStandardTracing~1standardTraceBadBlockToFile

  # debug/runtimeDebugging:
  /debug/runtimeDebugging/gcStats:
    $ref: ../../web3rpc/rpc-specs/paths/debug/runtimeDebugging/gcStats.yaml#/paths/~1debug~1runtimeDebugging~1gcStats
  /debug/runtimeDebugging/metrics:
    $ref: ../../web3rpc/rpc-specs/paths/debug/runtimeDebugging/metrics.yaml#/paths/~1debug~1runtimeDebugging~1metrics
  /debug/runtimeDebugging/stacks:
    $ref: ../../web3rpc/rpc-specs/paths/debug/runtimeDebugging/stacks.yaml#/paths/~1debug~1runtimeDebugging~1stacks
  /debug/runtimeDebugging/freeOSMemory:
    $ref: ../../web3rpc/rpc-specs/paths/debug/runtimeDebugging/freeOSMemory.yaml#/paths/~1debug~1runtimeDebugging~1freeOSMemory
  /debug/runtimeDebugging/setGCPercent:
    $ref: ../../web3rpc/rpc-specs/paths/debug/runtimeDebugging/setGCPercent.yaml#/paths/~1debug~1runtimeDebugging~1setGCPercent
  /debug/runtimeDebugging/memStats:
    $ref: ../../web3rpc/rpc-specs/paths/debug/runtimeDebugging/memStats.yaml#/paths/~1debug~1runtimeDebugging~1memStats

  # debug/profiling:
  /debug/profiling/startPProf:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/startPProf.yaml#/paths/~1debug~1profiling~1startPProf
  /debug/profiling/stopPProf:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/stopPProf.yaml#/paths/~1debug~1profiling~1stopPProf
  /debug/profiling/blockProfile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/blockProfile.yaml#/paths/~1debug~1profiling~1blockProfile
  /debug/profiling/cpuProfile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/cpuProfile.yaml#/paths/~1debug~1profiling~1cpuProfile
  /debug/profiling/mutexProfile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/mutexProfile.yaml#/paths/~1debug~1profiling~1mutexProfile
  /debug/profiling/setBlockProfileRate:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/setBlockProfileRate.yaml#/paths/~1debug~1profiling~1setBlockProfileRate
  /debug/profiling/startCPUProfile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/startCPUProfile.yaml#/paths/~1debug~1profiling~1startCPUProfile
  /debug/profiling/stopCPUProfile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/stopCPUProfile.yaml#/paths/~1debug~1profiling~1stopCPUProfile
  /debug/profiling/writeBlockProfile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/writeBlockProfile.yaml#/paths/~1debug~1profiling~1writeBlockProfile
  /debug/profiling/writeMemProfile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/writeMemProfile.yaml#/paths/~1debug~1profiling~1writeMemProfile
  /debug/profiling/writeMutexProfile:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/writeMutexProfile.yaml#/paths/~1debug~1profiling~1writeMutexProfile
  /debug/profiling/isPProfRunning:
    $ref: ../../web3rpc/rpc-specs/paths/debug/profiling/isPProfRunning.yaml#/paths/~1debug~1profiling~1isPProfRunning

  # debug/runtimeTracing:
  /debug/runtimeTracing/goTrace:
    $ref: ../../web3rpc/rpc-specs/paths/debug/runtimeTracing/goTrace.yaml#/paths/~1debug~1runtimeTracing~1goTrace
  /debug/runtimeTracing/startGoTrace:
    $ref: ../../web3rpc/rpc-specs/paths/debug/runtimeTracing/startGoTrace.yaml#/paths/~1debug~1runtimeTracing~1startGoTrace
  /debug/runtimeTracing/stopGoTrace:
    $ref: ../../web3rpc/rpc-specs/paths/debug/runtimeTracing/stopGoTrace.yaml#/paths/~1debug~1runtimeTracing~1stopGoTrace
