openapi: "3.0.2"
info:
  title: web3rpc
  version: "0.9.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
x-tagGroups:
  - name: namespaces
    tags:
      - kaia
servers:
  - url: https://public-en-kairos.node.kaia.io
  - url: https://public-en.node.kaia.io
  - url: http://localhost:8551
paths:
  # kaia/account
  /kaia/account/accountCreated:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/accountCreated.yaml#/paths/~1kaia~1account~1accountCreated
  /kaia/account/accounts:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/accounts.yaml#/paths/~1kaia~1account~1accounts
  /kaia/account/decodeAccountKey:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/decodeAccountKey.yaml#/paths/~1kaia~1account~1decodeAccountKey
  /kaia/account/getAccountKey:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/getAccountKey.yaml#/paths/~1kaia~1account~1getAccountKey
  /kaia/account/getCode:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/getCode.yaml#/paths/~1kaia~1account~1getCode
  /kaia/account/encodeAccountKey:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/encodeAccountKey.yaml#/paths/~1kaia~1account~1encodeAccountKey
  /kaia/account/getAccount:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/getAccount.yaml#/paths/~1kaia~1account~1getAccount
  /kaia/account/getBalance:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/getBalance.yaml#/paths/~1kaia~1account~1getBalance
  /kaia/account/sign:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/sign.yaml#/paths/~1kaia~1account~1sign
  /kaia/account/getTransactionCount:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/getTransactionCount.yaml#/paths/~1kaia~1account~1getTransactionCount
  /kaia/account/isContractAccount:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/account/isContractAccount.yaml#/paths/~1kaia~1account~1isContractAccount

  # kaia/block
  /kaia/block/blockNumber:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/blockNumber.yaml#/paths/~1kaia~1block~1blockNumber
  /kaia/block/getBlockByHash:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getBlockByHash.yaml#/paths/~1kaia~1block~1getBlockByHash
  /kaia/block/getBlockReceipts:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getBlockReceipts.yaml#/paths/~1kaia~1block~1getBlockReceipts
  /kaia/block/getBlockTransactionCountByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getBlockTransactionCountByNumber.yaml#/paths/~1kaia~1block~1getBlockTransactionCountByNumber
  /kaia/block/getBlockWithConsensusInfoByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getBlockWithConsensusInfoByNumber.yaml#/paths/~1kaia~1block~1getBlockWithConsensusInfoByNumber
  /kaia/block/getCommittee:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getCommittee.yaml#/paths/~1kaia~1block~1getCommittee
  /kaia/block/getCommitteeSize:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getCommitteeSize.yaml#/paths/~1kaia~1block~1getCommitteeSize
  /kaia/block/getCouncil:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getCouncil.yaml#/paths/~1kaia~1block~1getCouncil
  /kaia/block/getCouncilSize:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getCouncilSize.yaml#/paths/~1kaia~1block~1getCouncilSize
  /kaia/block/getBlockByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getBlockByNumber.yaml#/paths/~1kaia~1block~1getBlockByNumber
  /kaia/block/getBlockTransactionCountByHash:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getBlockTransactionCountByHash.yaml#/paths/~1kaia~1block~1getBlockTransactionCountByHash
  /kaia/block/getHeaderByNumber:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getHeaderByNumber.yaml#/paths/~1kaia~1block~1getHeaderByNumber
  /kaia/block/getHeaderByHash:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getHeaderByHash.yaml#/paths/~1kaia~1block~1getHeaderByHash
  /kaia/getRewards:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getRewards.yaml#/paths/~1kaia~1block~1getRewards
  /kaia/getStorageAt:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getStorageAt.yaml#/paths/~1kaia~1block~1getStorageAt
  /kaia/block/syncing:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/syncing.yaml#/paths/~1kaia~1block~1syncing
  /kaia/block/getBlockWithConsensusInfoByNumberRange:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getBlockWithConsensusInfoByNumberRange.yaml#/paths/~1kaia~1block~1getBlockWithConsensusInfoByNumberRange
  /kaia/block/getBlockWithConsensusInfoByHash:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/block/getBlockWithConsensusInfoByHash.yaml#/paths/~1kaia~1block~1getBlockWithConsensusInfoByHash

  # kaia/transaction
  /kaia/transaction/call:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/call.yaml#/paths/~1kaia~1transaction~1call
  /kaia/transaction/getDecodedAnchoringTransactionByHash:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getDecodedAnchoringTransactionByHash.yaml#/paths/~1kaia~1transaction~1getDecodedAnchoringTransactionByHash
  /kaia/transaction/estimateGas:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/estimateGas.yaml#/paths/~1kaia~1transaction~1estimateGas
  /kaia/transaction/getTransactionByBlockNumberAndIndex:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getTransactionByBlockNumberAndIndex.yaml#/paths/~1kaia~1transaction~1getTransactionByBlockNumberAndIndex
  /kaia/transaction/getTransactionBySenderTxHash:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getTransactionBySenderTxHash.yaml#/paths/~1kaia~1transaction~1getTransactionBySenderTxHash
  /kaia/transaction/getTransactionByBlockHashAndIndex:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getTransactionByBlockHashAndIndex.yaml#/paths/~1kaia~1transaction~1getTransactionByBlockHashAndIndex
  /kaia/transaction/getTransactionByHash:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getTransactionByHash.yaml#/paths/~1kaia~1transaction~1getTransactionByHash
  /kaia/transaction/getTransactionReceipt:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getTransactionReceipt.yaml#/paths/~1kaia~1transaction~1getTransactionReceipt
  /kaia/transaction/sendRawTransaction:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/sendRawTransaction.yaml#/paths/~1kaia~1transaction~1sendRawTransaction
  /kaia/transaction/estimateComputationCost:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/estimateComputationCost.yaml#/paths/~1kaia~1transaction~1estimateComputationCost
  /kaia/transaction/sendTransaction:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/sendTransaction.yaml#/paths/~1kaia~1transaction~1sendTransaction
  /kaia/transaction/sendTransactionAsFeePayer:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/sendTransactionAsFeePayer.yaml#/paths/~1kaia~1transaction~1sendTransactionAsFeePayer
  /kaia/transaction/signTransaction:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/signTransaction.yaml#/paths/~1kaia~1transaction~1signTransaction
  /kaia/transaction/signTransactionAsFeePayer:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/signTransactionAsFeePayer.yaml#/paths/~1kaia~1transaction~1signTransactionAsFeePayer
  /kaia/transaction/pendingTransactions:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/pendingTransactions.yaml#/paths/~1kaia~1transaction~1pendingTransactions
  /kaia/transaction/getTransactionReceiptBySenderTxHash:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getTransactionReceiptBySenderTxHash.yaml#/paths/~1kaia~1transaction~1getTransactionReceiptBySenderTxHash
  /kaia/createAccessList:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/createAccessList.yaml#/paths/~1kaia~1transaction~1createAccessList
  /kaia/getRawTransactionByBlockHashAndIndex:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getRawTransactionByBlockHashAndIndex.yaml#/paths/~1kaia~1transaction~1getRawTransactionByBlockHashAndIndex
  /kaia/getRawTransactionByHash:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getRawTransactionByHash.yaml#/paths/~1kaia~1transaction~1getRawTransactionByHash
  /kaia/resend:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/resend.yaml#/paths/~1kaia~1transaction~1resend
  /kaia/getRawTransactionByBlockNumberAndIndex:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/transaction/getRawTransactionByBlockNumberAndIndex.yaml#/paths/~1kaia~1transaction~1getRawTransactionByBlockNumberAndIndex

  # kaia/configuration
  /kaia/configuration/chainID:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/chainID.yaml#/paths/~1kaia~1configuration~1chainID
  /kaia/configuration/clientVersion:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/clientVersion.yaml#/paths/~1kaia~1configuration~1clientVersion
  /kaia/configuration/gasPrice:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/gasPrice.yaml#/paths/~1kaia~1configuration~1gasPrice
  /kaia/configuration/isParallelDBWrite:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/isParallelDBWrite.yaml#/paths/~1kaia~1configuration~1isParallelDBWrite
  /kaia/configuration/isSenderTxHashIndexingEnabled:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/isSenderTxHashIndexingEnabled.yaml#/paths/~1kaia~1configuration~1isSenderTxHashIndexingEnabled
  /kaia/configuration/protocolVersion:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/protocolVersion.yaml#/paths/~1kaia~1configuration~1protocolVersion
  /kaia/configuration/rewardbase:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/rewardBase.yaml#/paths/~1kaia~1configuration~1rewardbase
  /kaia/configuration/getChainConfig:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/getChainConfig.yaml#/paths/~1kaia~1configuration~1getChainConfig
  /kaia/configuration/forkStatus:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/forkStatus.yaml#/paths/~1kaia~1configuration~1forkStatus
  /kaia/configuration/getParams:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/configuration/getParams.yaml#/paths/~1kaia~1configuration~1getParams

  # kaia/filter
  /kaia/filter/getFilterChanges:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/filter/getFilterChanges.yaml#/paths/~1kaia~1filter~1getFilterChanges
  /kaia/filter/getFilterLogs:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/filter/getFilterLogs.yaml#/paths/~1kaia~1filter~1getFilterLogs
  /kaia/filter/newBlockFilter:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/filter/newBlockFilter.yaml#/paths/~1kaia~1filter~1newBlockFilter
  /kaia/filter/newPendingTransactionFilter:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/filter/newPendingTransactionFilter.yaml#/paths/~1kaia~1filter~1newPendingTransactionFilter
  /kaia/filter/uninstallFilter:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/filter/uninstallFilter.yaml#/paths/~1kaia~1filter~1uninstallFilter
  /kaia/filter/unsubscribe:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/filter/unsubscribe.yaml#/paths/~1kaia~1filter~1unsubscribe
  /kaia/filter/getLogs:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/filter/getLogs.yaml#/paths/~1kaia~1filter~1getLogs
  /kaia/filter/subscribe:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/filter/subscribe.yaml#/paths/~1kaia~1filter~1subscribe
  /kaia/filter/newFilter:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/filter/newFilter.yaml#/paths/~1kaia~1filter~1newFilter

  # kaia/gas
  /kaia/gas/feeHistory:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/gas/feeHistory.yaml#/paths/~1kaia~1gas~1feeHistory
  /kaia/gas/lowerBoundGasPrice:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/gas/lowerBoundGasPrice.yaml#/paths/~1kaia~1gas~1lowerBoundGasPrice
  /kaia/gas/upperBoundGasPrice:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/gas/upperBoundGasPrice.yaml#/paths/~1kaia~1gas~1upperBoundGasPrice
  /kaia/gas/maxPriorityFeePerGas:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/gas/maxPriorityFeePerGas.yaml#/paths/~1kaia~1gas~1maxPriorityFeePerGas

  # kaia/miscellaneous
  /kaia/miscellaneous/sha3:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/miscellaneous/sha3.yaml#/paths/~1kaia~1miscellaneous~1sha3
  /kaia/miscellaneous/getStakingInfo:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/miscellaneous/getStakingInfo.yaml#/paths/~1kaia~1miscellaneous~1getStakingInfo
  /kaia/miscellaneous/recoverFromTransaction:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/miscellaneous/recoverFromTransaction.yaml#/paths/~1kaia~1miscellaneous~1recoverFromTransaction
  /kaia/miscellaneous/recoverFromMessage:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/miscellaneous/recoverFromMessage.yaml#/paths/~1kaia~1miscellaneous~1recoverFromMessage
  /kaia/miscellaneous/getProof:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/miscellaneous/getProof.yaml#/paths/~1kaia~1miscellaneous~1getProof
  /kaia/miscellaneous/nodeAddress:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/miscellaneous/nodeAddress.yaml#/paths/~1kaia~1miscellaneous~1nodeAddress
  /kaia/miscellaneous/getTotalSupply:
    $ref: ../../web3rpc/rpc-specs/paths/kaia/miscellaneous/getTotalSupply.yaml#/paths/~1kaia~1miscellaneous~1getTotalSupply
