openapi: "3.0.2"
info:
  title: web3rpc
  version: "0.9.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
x-tagGroups:
  - name: namespaces
    tags:
      - mainbridge
servers:
  - url: https://public-en-kairos.node.kaia.io
  - url: https://public-en.node.kaia.io
  - url: http://localhost:8551
paths:

  # mainbridge:
  /mainbridge/convertChildChainBlockHashToParentChainTxHash:
    $ref: ../../web3rpc/rpc-specs/paths/mainbridge/convertChildChainBlockHashToParentChainTxHash.yaml#/paths/~1mainbridge~1convertChildChainBlockHashToParentChainTxHash
  /mainbridge/getChildChainIndexingEnabled:
    $ref: ../../web3rpc/rpc-specs/paths/mainbridge/getChildChainIndexingEnabled.yaml#/paths/~1mainbridge~1getChildChainIndexingEnabled
  /mainbridge/nodeInfo:
    $ref: ../../web3rpc/rpc-specs/paths/mainbridge/nodeInfo.yaml#/paths/~1mainbridge~1nodeInfo
  /mainbridge/addPeer:
    $ref: ../../web3rpc/rpc-specs/paths/mainbridge/addPeer.yaml#/paths/~1mainbridge~1addPeer
  /mainbridge/removePeer:
    $ref: ../../web3rpc/rpc-specs/paths/mainbridge/removePeer.yaml#/paths/~1mainbridge~1removePeer