openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/transaction/getRawTransactionByBlockNumberAndIndex:
    post:
      operationId: getRawTransactionByBlockNumberAndIndex
      summary: "[Transaction] eth_getRawTransactionByBlockNumberAndIndex"
      tags:
        - eth
      description: |
        GetRawTransactionByBlockNumberAndIndex returns the bytes of the transaction for the given block number and index.

        **JSONRPC:** `eth_getRawTransactionByBlockNumberAndIndex`

      parameters:
        - name: blockNumberOrTag
          in: query
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
        - name: index
          required: true
          schema:
            type: string
            format: hex
          description: Hex representation of a uint
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/EthGetRawTransactionByBlockNumberAndIndexReq"

      responses:
        200:
          description: Returns the bytes of the transaction for the given block number and index.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthGetRawTransactionByBlockNumberAndIndexResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/others/getRawTransactionByBlockNumberAndIndex.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/others/EthGetRawTransactionByBlockNumberAndIndexExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/transaction/getRawTransactionByBlockNumberAndIndex.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/eth/others/getRawTransactionByBlockNumberAndIndex.py"

components:
  schemas:
    EthGetRawTransactionByBlockNumberAndIndexReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'eth_getRawTransactionByBlockNumberAndIndex'
        params:
          type: array
          items:
            properties:
              BlockNumberOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
              TransactionIndex:
                title: TransactionIndexPosition
                description: Integer of the transaction index position.
                type: string
                format: hex
          example:  [118593751, "0x0"]

    EthGetRawTransactionByBlockNumberAndIndexResp:
      type: object
      properties:
        result:
          type: string
          format: hex
          description: Hex representation of some bytes
          example: "0x0"
