openapi: "3.0.2"
info:
  title: KAIA Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/gas/maxPriorityFeePerGas:
    post:
      summary: "[Gas] eth_maxPriorityFeePerGas"
      tags:
        - eth
      operationId: maxPriorityFeePerGas
      description: |
        Returns a recommended maxPriorityFeePerGas for a new transaction.

        - Before Magma, returns the fixed UnitPrice
        - After Magma, returns zero
        - After Kaia, returns zero if network is uncongested (i.e. next baseFee at its lower bound), otherwise 60% percentile effective tip from previous 20 blocks (under default setting)

        **NOTE:** This API has different behavior from Ethereum's and returns a gas price of Kaia instead of suggesting a gas price as in Ethereum.

        **JSONRPC:** `eth_maxPriorityFeePerGas`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/EthMaxPriorityFeePerGasReq"

      responses:
        200:
          description: Recommended maxPriorityFeePerGas in kei.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthMaxPriorityFeePerGasResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/gas/maxPriorityFeePerGas.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/gas/EthMaxPriorityFeePerGasExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/gas/maxPriorityFeePerGas.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/eth/gas/maxPriorityFeePerGas.py"

components:
  schemas:
    EthMaxPriorityFeePerGasReq:
      type: object
      properties:
        method:
          type: string
          default: 'eth_maxPriorityFeePerGas'

    EthMaxPriorityFeePerGasResp:
      type: object
      properties:
        result:
          type: string
          description: Recommended maxPriorityFeePerGas in kei.
          format: hex
          example: "0xAE9F7BCC00"