openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /admin/importChain:
    post:
      operationId: importChain
      summary: "admin_importChain"
      description: |
        The importChain is an administrative method that imports an exported chain from a file into a node. This method imports only blocks that haven't existed in a Kaia node. This method does not delete any data of the existing chain.
       
        **JSONRPC:** `admin_importChain`

      tags:
        - admin

      parameters:
        - name: fileName
          required: true
          schema:
            type: string
          description: the fully qualified path to the file containing the chain to be imported.
          in: query
  
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/ImportChainReq"

      responses:
        200:
          description: true if chain was imported, false if not.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/ImportChainResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/admin/importChain.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/admin/AdminImportChainExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
           $ref: "../../code-samples/javascript/admin/importChainApi.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/admin/importChain.py"

components:
  schemas:
    ImportChainReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'admin_importChain'
        params:
          type: array
          description: the fully qualified path to the file containing the chain to be imported.
          items:
            title: FileName
            type: string
          example: ["/tmp/chain.txt"]

    ImportChainResp:
      type: object
      properties:
        result:
          type: boolean
          description: true if chain was imported, false if not.
          example: true
