openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /admin/setSpamThrottlerWhiteList:
    post:
      operationId: setSpamThrottlerWhiteList
      summary: "admin_setSpamThrottlerWhiteList"
      description: |
        Set spam throttler white list

        **JSONRPC:** `admin_setSpamThrottlerWhiteList`

      tags:
        - admin

      parameters:
        - name: addresses
          required: true
          schema:
            type: array
            items:
              $ref: "../../components/schemas/common/Common.yaml#/components/schemas/Address"
            description: list of address to put to spam white list
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/SetSpamThrottlerWhiteListReq"

      responses:
        200:
          description: Set spam throttler white list
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/SetSpamThrottlerWhiteListResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/admin/setSpamThrottlerWhiteList.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/admin/AdminSetSpamThrottlerWhiteListExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
           $ref: "../../code-samples/javascript/admin/setSpamThrottlerWhiteList.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/admin/setSpamThrottlerWhiteList.py"

components:
  schemas:
    SetSpamThrottlerWhiteListReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'admin_setSpamThrottlerWhiteList'
        params:
          type: array
          items:
            $ref: "../../components/schemas/common/Common.yaml#/components/schemas/Address"
          example: [["0xfdeedbb2fe5b48d5b49e435ba00e0358740d0cf5"]]

    SetSpamThrottlerWhiteListResp:
      type: object
      properties:
        result:
          type: string
          example: null