openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /admin/startHTTP:
    post:
      operationId: startHTTP
      summary: "admin_startHTTP"
      description: |
        The startHTTP is an administrative method that starts an HTTP based JSON RPC API webserver to handle client requests.

        The method returns a boolean flag specifying whether the HTTP RPC listener was opened or not. Please note, only one HTTP endpoint is allowed to be active at any time.

        **NOTE:** *This API replaces admin_startRPC. The admin_startRPC will be deprecated soon.*

        **JSONRPC:** `admin_startHTTP`

      tags:
        - admin

      parameters:
        - name: host
          schema:
            type: string
          description: (optional) network interface to open the listener socket on (default "localhost").
          in: query
        - name: port
          schema:
            type: integer
          description: (optional) network port to open the listener socket on (default 8551).
          in: query
        - name: cors
          schema:
            type: string
          description: (optional) cross-origin resource sharing header to use (default "").
          in: query
        - name: apis
          schema:
            type: string
          description: (optional) API modules to offer over this interface (default "klay,net,rpc").
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/StartHTTPReq"

      responses:
        200:
          description: Return true if the HTTP RPC listener was opened, false if not.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/StartHTTPResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/admin/startHTTP.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/admin/AdminStartHTTPExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
           $ref: "../../code-samples/javascript/admin/startHTTP.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/admin/startHTTP.py"

components:
  schemas:
    StartHTTPReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'admin_startHTTP'
        params:
          type: array
          items:
            properties:
              Host:
                type: string
                title: Host
                description: (optional) network interface to open the listener socket on (default "localhost").
              Port:
                type: integer
                title: Port
                description: (optional) network port to open the listener socket on (default 8551).
              Cors:
                type: string
                title: Cors
                description: (optional) cross-origin resource sharing header to use (default "").
              APIs:
                type: string
                title: Apis
                description: (optional) API modules to offer over this interface (default "klay,net,rpc").
          example:
            ["127.0.0.1", 8551, "", "klay"]

    StartHTTPResp:
      type: object
      properties:
        result:
          type: boolean
          description: true if the HTTP RPC listener was opened, false if not.
          example: true





