openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /admin/stopHTTP:
    post:
      operationId: stopHTTP
      summary: "admin_stopHTTP"
      description: |
        The stopHTTP is an administrative method that closes the currently open HTTP RPC endpoint. As the node can only have a single HTTP endpoint running, this method takes no parameters, returning a boolean whether the endpoint was closed or not.

        **NOTE:** This API replaces admin_stopRPC. The admin_stopRPC will be deprecated soon.

        **JSONRPC:** `admin_stopHTTP`

      tags:
        - admin

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/StopHTTPReq"

      responses:
        200:
          description: true if the endpoint was closed, false if not.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/StopHTTPResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/admin/stopHTTP.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/admin/AdminStopHTTPExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
           $ref: "../../code-samples/javascript/admin/stopHTTP.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/admin/stopHTTP.py"

components:
  schemas:
    StopHTTPReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'admin_stopHTTP'

    StopHTTPResp:
      type: object
      properties:
        result:
          type: boolean
          description: true if the endpoint was closed, false if not.
          example: true





