openapi: "3.0.2"
info:
  title: KAIA Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /subbridge/addPeer:
    post:
      summary: "subbridge_addPeer"
      tags:
        - subbridge
      operationId: addPeer
      description: |
        Returns true if adding a mainbridge peer is done successfully.
        
        The addPeer method adds a new remote node to the peer list. The node will try to maintain connectivity to these nodes at all times, reconnecting every once in a while if the remote connection goes down.
        
        The method accepts a single argument, the kni URL of the remote peer to start tracking and returns a BOOL indicating whether the peer was accepted for tracking or some error occurred.

        **JSONRPC:** `subbridge_addPeer`

      parameters:
        - name: url
          required: true
          schema:
            type: string
          description: Peer's kni URL.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/AddPeerReq"

      responses:
        200:
          description: true if the peer was accepted, false otherwise.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/AddPeerResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/subbridge/addPeer.sh"
        # - lang: "Java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "JavaScript"
        #   label: "Javascript"
        #   source:
        #     $ref: "../../../code-samples/javascript/eth/miscellaneous/txPending.js"
        # - lang: "Python"
        #   label: "Python"
        #   source:
        #     $ref: "../../../code-samples/python/eth/miscellaneous/txPending.py"

components:
  schemas:
    AddPeerReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'subbridge_addPeer'
        params: 
          type: array
          description: Peer's kni URL.
          items: 
            type: string
            title: Url
          example: ["kni://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@10.0.0.1:50505"]

    AddPeerResp:
      type: object
      properties:
        result:
          type: boolean
          description: true if the peer was accepted, false otherwise.
          example: true