openapi: "3.0.2"
info:
  title: KAIA Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /subbridge/anchoring:
    post:
      summary: "subbridge_anchoring"
      tags:
        - subbridge
      operationId: anchoring
      description: |
        The subbridge_anchoring can enable/disable the anchoring feature of the service chain.
        
        **JSONRPC:** `subbridge_anchoring`

      parameters:
        - name: enable
          required: true
          schema:
            type: boolean
          description: true enables the anchoring feature, false disables it.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/AnchoringReq"

      responses:
        200:
          description: true if the anchoring was enabled, false otherwise.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/AnchoringResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/subbridge/anchoring.sh"
        # - lang: "Java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "JavaScript"
        #   label: "Javascript"
        #   source:
        #     $ref: "../../../code-samples/javascript/eth/miscellaneous/txPending.js"
        # - lang: "Python"
        #   label: "Python"
        #   source:
        #     $ref: "../../../code-samples/python/eth/miscellaneous/txPending.py"

components:
  schemas:
    AnchoringReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'subbridge_anchoring'
        params: 
          type: array
          description: true enables the anchoring feature, false disables it.
          items: 
            type: string
            title: Enable
          example: [true]

    AnchoringResp:
      type: object
      properties:
        result:
          type: boolean
          description: true if the anchoring was enabled, false otherwise.
          example: true