openapi: "3.0.2"
info:
  title: KAIA Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /subbridge/registerBridge:
    post:
      summary: "subbridge_registerBridge"
      tags:
        - subbridge
      operationId: registerBridge
      description: |
        The subbridge_registerBridge registers already deployed bridge contracts in the parent and child chains.

        **JSONRPC:** `subbridge_registerBridge`

      parameters:
        - name: childAccount
          in: query
          required: true
          description: Address of bridge contract on child chain.
          schema:
            $ref: "../../components/schemas/common/Common.yaml#/components/schemas/Address"
        - name: parentAccount
          in: query
          required: true
          description: Address of bridge contract on parent chain.
          schema:
            $ref: "../../components/schemas/common/Common.yaml#/components/schemas/Address"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/SubbridgeRegisterBridgeReq"

      responses:
        200:
          description: The subbridge_registerBridge registers already deployed bridge contracts in the parent and child chains.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/SubbridgeRegisterBridgeResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/subbridge/registerBridge.sh"
        # - lang: "Java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "JavaScript"
        #   label: "Javascript"
        #   source:
        #     $ref: "../../code-samples/javascript/eth/miscellaneous/registerBridge.js"
        # - lang: "Python"
        #   label: "Python"
        #   source:
        #     $ref: "../../code-samples/python/eth/miscellaneous/registerBridge.py"

components:
  schemas:
    SubbridgeRegisterBridgeReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'subbridge_registerBridge'
        params:
          type: array
          items:
            properties:
              ChildAccount:
                title: ChildAccount
                type: string
                format: 20-byte DATA
                description: Address of bridge contract on child chain.
              ParentAccount:
                title: ParentAccount
                type: string
                format: 20-byte DATA
                description: Address of bridge contract on parent chain.
          example: ["0x87d6b9c567e5b84cd00e03bfbe6d20d88209c33a", "0x23dab942822021bbd6d551ef51003208924877e4"]

    SubbridgeRegisterBridgeResp:
      type: object
      properties:
        result:
          type: string
          example: null
          description: null if the registration succeeds, Error object otherwise.
          # error