openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/transaction/createAccessList:
    post:
      operationId: createAccessList
      summary: "[Transaction] klay_createAccessList"
      description: |
        This method creates an accessList based on a given Transaction. The accessList contains all storage slots and addresses read and written by the transaction, except for the sender account and the precompiles. This method uses the same transaction call object and blockNumberOrTag object as caver.rpc.klay.call. An accessList can be used to release stuck contracts that became inaccessible due to gas cost increases. Adding an accessList to your transaction does not necessary result in lower gas usage compared to a transaction without an access list.

        **JSONRPC:** `klay_createAccessList`

      tags:
        - klay

      parameters:
        - name: callObject
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/KlayCallObject"
          description: A transaction call object. Please see caver.rpc.klay.call parameters.
          in: query
        - name: blockParameter
          in: query
          description: (optional) A block number, blockhash or the block tag string (latest or earliest). If omitted, latest will be used.
          required: false
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayCreateAccessListReq"

      responses:
        200:
          description: returns an object includes an access list
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayCreateAccessListResp"


      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/others/createAccessList.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/others/KlayCreateAccessListExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/others/createAccessList.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/others/createAccessList.py"
components:
  schemas:
    KlayCreateAccessListReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_createAccessList'
        params:
          type: array
          items:
            properties:
              CallObject:
                title: CallObject
                description: A transaction call object. Please see caver.rpc.klay.call parameters.
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/KlayCallObject"
              BlockParameter:
                title: blockParameter
                description: (optional) A block number, blockhash or the block tag string (latest or earliest). If omitted, latest will be used.
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"
          example:  [
            {
              "from": "0x3bc5885c2941c5cda454bdb4a8c88aa7f248e312",
              "to": "0x00f5f5f3a25f142fafd0af24a754fafa340f32c7",
              "gas": "0x3d0900",
              "gasPrice": "0x3b9aca00",
              "data": "0x20965255"
            },
            "latest"
          ]

    KlayCreateAccessListResp:
      type: object
      properties:
        result:
          type: object
          required:
            - accessList
            - gasUsed
          properties:
            accessList:
              type: array
              items:
                type: object
                required:
                  - oldestBlock
                  - reward
                  - baseFeePerGas
                  - gasUsedRatio
                properties:
                  oldestBlock:
                    type: string
                    description: Lowest number block of returned range.
                  reward:
                    description: A two-dimensional array of effective priority fees per gas at the requested block percentiles.
                    type: array
                    items:
                      type: array
                      items:
                        type: string
                  baseFeePerGas:
                    description: An array of block base fees per gas. This includes the next block after the newest of the returned range, because this value can be derived from the newest block. Zeroes are returned for pre-EIP-1559 blocks.
                    type: array
                    items:
                      type: string
                  gasUsedRatio:
                    description: An array of gasUsed/gasLimit in the block.
                    type: array
                    items:
                      type: string
                      format: hex
            gasUsed:
              type: string
              format: hex
          example: { accessList: [], gasUsed: '0x0' }

