openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /governance/getParams:
    post:
      operationId: getParams
      summary: "governance_getParams"
      description: |
        The getParams returns governance items at specific block.

        **WARNING:** governance_getParams API will be deprecated since Kaia v1.11 (see klaytn#1783). Use governance_getParams instead.

        **NOTE:** In versions earlier than Kaia v1.7.0, only integer block number, the string "earliest" and "latest" are available.

        **NOTE:** The block number can be larger than the latest block number, in which case the API returns the tentative value based on the current chain state. The future governance parameters are subject to change via additional governance votes or GovParam contract state changes.

        **JSONRPC:** `governance_getParams`

      tags:
        - governance

      parameters:
        - name: blockNumber
          required: true
          schema:
            $ref: "../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  required:
                    - method
                    - params
                  properties:
                    method:
                      type: string
                      default: 'governance_getParams'
                    params:
                      type: array
                      items:
                        $ref: "../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
                      example: [0]

      responses:
        200:
          description: governance items
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: object
                        description: governance items
                        example: {
                          governance.governancemode: "single",
                          governance.governingnode: "0x7bf29f69b3a120dae17bca6cf344cf23f2daf208",
                          governance.unitprice: 25000000000,
                          istanbul.committeesize: 13,
                          istanbul.epoch: 30,
                          istanbul.policy: 2,
                          kip71.basefeedenominator: 20,
                          kip71.gastarget: 30000000,
                          kip71.lowerboundbasefee: 25000000000,
                          kip71.maxblockgasusedforbasefee: 60000000,
                          kip71.upperboundbasefee: 750000000000,
                          reward.deferredtxfee: true,
                          reward.minimumstake: "5000000",
                          reward.mintingamount: "9600000000000000000",
                          reward.proposerupdateinterval: 30,
                          reward.ratio: "34/54/12",
                          reward.stakingupdateinterval: 60,
                          reward.useginicoeff: true
                        }

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/governance/getParams.sh"
        # - lang: "Java"
        #   label: "Java"
        #   source:
        #     $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/governance/GovernancegetParamsExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/governance/getParams.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/governance/getParams.py"
