openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /governance/getRewardsAccumulated:
    post:
      operationId: getRewardsAccumulated
      summary: "governance_getRewardsAccumulated"
      description: |
        Returns the accumulated block rewards distribution in the given block number range. This is essentially a sum of kaia_getRewards outputs.

        **NOTE**: Prior to Kaia v2.0.0, the firstBlockTime and lastBlockTime fields were human-readable time string. In Kaia v2.0.0 or later, the fields are unix timestamps.

        **JSONRPC:** `governance_getRewardsAccumulated`

      tags:
        - governance

      parameters:
        - name: first
          required: true
          schema:
            $ref: "../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"
          description: First block of the range, inclusive.
          in: query
        - name: last
          required: true
          schema:
            $ref: "../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrHashOrTag"
          description: Last block of the range, inclusive.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  required:
                    - method
                    - params
                  properties:
                    method:
                      type: string
                      default: 'governance_getRewardsAccumulated'
                    params:
                      type: array
                      items:
                        anyOf:
                          - title: firstBlock
                            description: the block number with type integer
                            type: number
                          - title: lastBlock
                            description: the block number with type integer
                            type: number
                      description: Integer of a block number.
                      example: [123400489,123416489]

      responses:
        200:
          description: Returns the accumulated reward distribution details.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: object
                        description: Accumulated reward information in a given block range
                        properties:
                          firstBlockTime:
                            type: number
                            format: integer
                          lastBlockTime:
                            type: number
                            format: integer
                          firstBlock:
                            type: number
                            format: integer
                          lastBlock:
                            type: number
                            format: integer
                          totalMinted:
                            type: number
                            format: integer
                          totalTxFee:
                            type: number
                            format: integer
                          totalBurntTxFee:
                            type: number
                            format: integer
                          totalProposerRewards:
                            type: number
                            format: integer
                          totalStakingRewards:
                            type: number
                            format: integer
                          totalKFFRewards:
                            type: number
                            format: integer
                          totalKCFRewards:
                            type: number
                            format: integer
                          rewards:
                            type: object
                        example: {
                          "firstBlockTime": 1561547992,
                          "lastBlockTime": 1561548008,
                          "firstBlock": 4096,
                          "lastBlock": 4112,
                          "totalMinted": 163200000000000000000,
                          "totalTxFee": 0,
                          "totalBurntTxFee": 0,
                          "totalProposerRewards": 163200000000000000000,
                          "totalStakingRewards": 0,
                          "totalKIFRewards": 0,
                          "totalKEFRewards": 0,
                          "rewards": {
                            "0x571e53df607be97431a5bbefca1dffe5aef56f4d": 38400000000000000000,
                            "0x5cb1a7dccbd0dc446e3640898ede8820368554c8": 48000000000000000000,
                            "0x99fb17d324fa0e07f23b49d09028ac0919414db6": 38400000000000000000,
                            "0xb74ff9dea397fe9e231df545eb53fe2adf776cb2": 38400000000000000000
                          }
                        }


      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/governance/getRewardsAccumulated.sh"
        - lang: "Java"
          label: "Java"
          source:
           $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/governance/GovernanceGetRewardsAccumulatedExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/governance/getRewardsAccumulated.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/governance/governance_getRewardsAccumulated.py"