openapi: "3.0.2"
info:
  title: KLAYTN OPEN API
  version: "1.10.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: governance
    description: API for governance namespace
servers:
  - url: http://localhost:7151
  - url: https://public-en-kairos.node.kaia.io
  - url: https://public-en.node.kaia.io
paths:
  # governance
  /governance/votes:
    $ref: ./votes.yaml#/paths/~1governance~1votes
  /governance/vote:
    $ref: ./vote.yaml#/paths/~1governance~1vote
  /governance/idxCache:
    $ref: ./idxCache.yaml#/paths/~1governance~1idxCache
  /governance/idxCacheFromDb:
    $ref: ./idxCacheFromDb.yaml#/paths/~1governance~1idxCacheFromDb
  /governance/nodeAddress:
    $ref: ./nodeAddress.yaml#/paths/~1governance~1nodeAddress
  /governance/pendingChanges:
    $ref: ./pendingChanges.yaml#/paths/~1governance~1pendingChanges
  /governance/chainConfig:
    $ref: ./chainConfig.yaml#/paths/~1governance~1chainConfig
  /governance/myVotingPower:
    $ref: ./myVotingPower.yaml#/paths/~1governance~1myVotingPower
  /governance/myVotes:
    $ref: ./myVotes.yaml#/paths/~1governance~1myVotes
  # /governance/itemsAt:
  #   $ref: ./itemsAt.yaml#/paths/~1governance~1itemsAt
  /governance/itemCacheFromDb:
    $ref: ./itemCacheFromDb.yaml#/paths/~1governance~1itemCacheFromDb
  /governance/getStakingInfo:
    $ref: ./getStakingInfo.yaml#/paths/~1governance~1getStakingInfo
  /governance/showTally:
    $ref: ./showTally.yaml#/paths/~1governance~1showTally
  /governance/totalVotingPower:
    $ref: ./totalVotingPower.yaml#/paths/~1governance~1totalVotingPower
  /governance/getParams:
    $ref: ./getParams.yaml#/paths/~1governance~1getParams
  /governance/getChainConfig:
    $ref: ./getChainConfig.yaml#/paths/~1governance~1getChainConfig
  /governance/getRewardsAccumulated:
    $ref: ./getRewardsAccumulated.yaml#/paths/~1governance~1getRewardsAccumulated