openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/blockchainInspection/getBadBlocks:
    post:
      operationId: getBadBlocks
      summary: "[Inspection] debug_getBadBlocks"
      description: |
        Returns a list of the last 'bad blocks' that the client has seen on the network.

        **JSONRPC:** `debug_getBadBlocks`
      tags:
        - debug

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  required:
                    - method
                  properties:
                    method:
                      type: string
                      default: debug_getBadBlocks

      responses:
        200:
          description: Return a list of the last 'bad blocks'.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: array
                        description: JSON list of block-hashes
                        items:
                          type: object
                        example: []
      
      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/blockchainInspection/getBadBlocks.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/blockchainInspection/DebugGetBadBlocksExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
           $ref: "../../../code-samples/javascript/debug/blockchainInspection/getBadBlocks.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/blockchainInspection/getBadBlocks.py"
