openapi: "3.0.2"
info:
  title: KAIA Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/blockchainInspection/preimage:
    post:
      summary: "[Inspection] debug_preimage"
      tags:
        - debug
      operationId: preimage
      description: |
        Returns the preimage for a sha3 hash, if known.

        :::note
        State-migrated databases may not contain preimages.
        :::

        **JSONRPC:** `debug_preimage`

      parameters:
        - name: hash
          in: query
          description: sha3 hash.
          required: true
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: debug_preimage
                    params:
                      type: array
                      description: sha3 hash.
                      items:
                        title: Hash
                        type: string
                        example: "0xaf953a2d01f55cfe080c0c94150a60105e8ac3d51153058a1f03dd239dd08586"

      responses:
        200:
          description: Returns the preimage for a sha3 hash, if known.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        title: preimage
                        type: string
                        description: Preimage for a sha3 hash.
                        example: "0xaf953a2d01f55cfe080c0c94150a60105e8ac3d51153058a1f03dd239dd08586"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/blockchainInspection/preimage.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/blockchainInspection/DebugPreimageExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/debug/blockchainInspection/preimage.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/blockchainInspection/preimage.py"
