openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/blockchainInspection/startContractWarmUp:
    post:
      operationId: startContractWarmUp
      summary: "[Inspection] debug_startContractWarmUp"
      description: |
        The startContractWarmUp iterates the latest storage trie of the given contract address to warm-up the trie cache. The iteration will be automatically stopped if 90% of the trie cache is full. The method returns an error if it fails in starting a warm-up or the given address is not a contract address, or null if it successfully has started it.

        **JSONRPC:** `debug_startContractWarmUp`

      tags:
        - debug

      parameters:
        - name: address
          in: query
          description: Contract address
          required: true
          schema:
            type: string
            format: 20-byte DATA

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: "debug_startContractWarmUp"
                    params:
                      type: array
                      items:
                        type: string
                      description: Contract address
                      example: ["0x4Cd39B49064a31E966cA0ddF4111aCe2eD7E9502"]

      responses:
        200:
          description: Return null if a warm-up is started, or an error if not.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        title: "StartContractWarmUpResult"
                        type: string
                        description: null if a warm-up is started, or an error if not.
                        example: null

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/blockchainInspection/startContractWarmUp.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/blockchainInspection/DebugStartContractWarmUpExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/debug/blockchainInspection/startContractWarmUp.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/blockchainInspection/startContractWarmUp.py"
