openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/inspection/gaslessInfo:
    post:
      operationId: gaslessInfo
      summary: "[Inspection] debug_gaslessInfo"
      description: |
        Returns the [KIP-247](https://kips.kaia.io/KIPs/kip-247) gasless module configuration.

        **JSONRPC:** `debug_gaslessInfo`

      tags:
        - debug

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  required:
                    - method
                    - params
                  properties:
                    method:
                      type: string
                      default: 'debug_gaslessInfo'

      responses:
        200:
          description: Returns if the transaction bundle is executable. If not, return the reason.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: object
                        description: "Returns if the transaction bundle is executable. If not, return the reason."
                        properties:
                          isDisabled:
                            type: boolean
                          swapRouter:
                            type: string
                          allowedTokens:
                            type: string[]
                          maxBundleTxs:
                            type: integer
                        example: {
                          jsonrpc: "2.0",
                          id: 1,
                          result: {
                            isDisabled: false,
                            swapRouter: "0x4b41783732810b731569e4d944f59372f411bea2",
                            allowedTokens: [
                              "0xcb00ba2cab67a3771f9ca1fa48fda8881b457750"
                            ],
                            maxBundleTxs: 100
                          }
                        }

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/inspection/gaslessInfo.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/inspection/DebugGaslessInfoExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/debug/inspection/gaslessInfo.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/inspection/gaslessInfo.py"