openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/runtimeDebugging/metrics:
    post:
      operationId: metrics
      summary: "[runtimeDebug] debug_metrics"
      description: |
        Retrieves all the known system metrics collected by the node.
        
        **JSONRPC:** `debug_metrics`

      tags:
        - debug

      parameters:
        - name: raw
          in: query
          description: true If raw data is output as it is, false If not
          required: true
          schema:
            type: boolean

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/MetricsReq"

      responses:
        200:
          description: The structured metrics collected by the node.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/MetricsResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/runtimeDebugging/metrics.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/runtimeDebugging/DebugMetricsExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/debug/runtimeDebugging/metrics.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/runtimeDebugging/metrics.py"

components:
  schemas:
    MetricsReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'debug_metrics'
        params: 
          description: true If raw data is output as it is, false If not
          items: 
            title: Raw
            type: boolean
          example: [true]

    MetricsResp:
      type: object
      properties:
        result:
            type: object
            description: The structured metrics collected by the node.
            example: 
                {"blockchain":
                  {"block":
                    {"tx":
                      {"counter":
                        {"Overall":98307},
                      "rate":{"AvgRate01Min":19.99999999999893,
                              "AvgRate05Min":19.999669059400787,
                              "AvgRate15Min":19.91097896398045,
                              "MeanRate":16.321034565305364,
                              "Overall":98307
                            }
                      }
                    },
                    "head":
                      {"blocknumber":"Unknown metric type"}
                  },
                  "bridgeTxpool":
                    {"refuse":{"Overall":0}},
                       ..., 
                  "inserts":
                   {"AvgRate01Min":0.9999999999999988,
                    "AvgRate05Min":0.9999997215208508,
                    "AvgRate15Min":0.9986124269288207,
                    "MeanRate":0.9946322927570416,
                    "Overall":5991,
                    "Percentiles":
                      {"20":6229668,"5":5986862.3,"50":6585653,"80":6864326.2,"95":7486187.249999999}
                    }
                }
            
