openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /kaia/transaction/sendRawTransaction:
    post:
      operationId: .sendRawTransaction
      summary: "[Transaction] kaia_sendRawTransaction"
      description: |
        Creates a new message call transaction or a contract creation for signed transactions.

        **NOTE:** If you deployed a contract, use kaia_getTransactionReceipt to get the contract address.

        **JSONRPC:** `kaia_sendRawTransaction`

      tags:
        - kaia

      parameters:
        - name: singedTransactionData
          required: true
          schema:
            type: string
            format: DATA
          description: The signed transaction data.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KaiaSendRawTransactionReq"

      responses:
        200:
          description: Returns the transaction hash or the zero hash if the transaction is not yet available.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: 32-byte DATA
                        description: "The transaction hash or the zero hash if the transaction is not yet available."
                        example: "0xe670ec64341771606e55d6b4ca35a1a6b75ee3d5145a99d05921026d1527331"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/kaia/transaction/sendRawTransaction.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/kaia/transaction/KaiaSendRawTransactionExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/kaia/transaction/sendRawTransaction.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/kaia/transaction/sendRawTransaction.py"

components:
  schemas:
    KaiaSendRawTransactionReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'kaia_sendRawTransaction'
        params:
          type: array
          description: The signed transaction data.
          items:
            type: string
            format:  DATA
            title: SingedTransactionData
            description: The signed transaction data.
          example:  ["0xaca5d9a1ed8b86b1ef61431b2bedfc99a66eaefc3a7e1cffdf9ff53653956a67"]
