openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /net/listening:
    post:
      operationId: listening
      summary: "net_listening"
      description: |
        Returns true if the client is actively listening for network connections.
        
        **JSONRPC:** `net_listening`
      tags:
        - net
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: net_listening

      responses:
        200:
          description: Returns true if the client is actively listening for network connections.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: boolean
                        description: true when listening, otherwise false.
                        example: true

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../code-samples/curl/net/listening.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../code-samples/java/src/main/java/opensdk/sdk/apis/net/NetListeningExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../code-samples/javascript/net/listening.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../code-samples/python/net/listening.py"
