openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/miscellaneous/recoverFromMessage:
    post:
      operationId: recoverFromMessage
      summary: "[Miscellaneous] klay_recoverFromMessage"
      description: |
        This method recovers or verifies an ECDSA signature signed by a private key associated with the given address.
 
        The signature has to be signed by the private key that constitutes the account, e.g. "natural" private key of a Legacy account, one of the keys of a WeightedMultisig account.
        
        Both [EIP-191](https://eips.ethereum.org/EIPS/eip-191) and [KIP-97](https://kips.kaia.io/KIPs/kip-97) signatures are accepted.

        **JSONRPC:** `klay_recoverFromMessage`
      tags:
        - klay

      parameters:
        - name: address
          in: query
          description: Address
          required: true
          schema:
            type: string
            format: 20-byte DATA
        - name: message
          required: true
          schema:
            type: string
            format: N-byte DATA
          description: A Message.
          in: query
        - name: signature
          required: true
          schema:
            type: string
          description: The signature.
          in: query
        - name: blockNumberOrTag
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in default block parameter.
          required: false
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayRecoverFromMessageReq"

      responses:
        200:
          description: The result of recover from message.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        type: string
                        format: hex
                        example: "0xa2a8854b1802d8cd5de631e690817c253d6a9153"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/miscellaneous/recoverFromMessage.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/miscellaneous/KlayRecoverFromMessageExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/miscellaneous/recoverFromMessage.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/miscellaneous/recoverFromMessage.py"

components:
  schemas:
    KlayRecoverFromMessageReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_recoverFromMessage'
        params:
          type: array
          items:
            properties:
              Address:
                title: Address
                description: Address.
                type: string
                format: 20-byte DATA
              Message:
                title: Message
                description: A Message.
                type: string
                format: N-byte DATA
              Signature:
                type: string
                title: Signature
                description: The signature.
              BlockNumberOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
          example: ["0xA2a8854b1802D8Cd5De631E690817c253d6a9153", "0xdeadbeef", "0x1e6338d6e4a8d688a25de78cf2a92efec9a92e52eb8425acaaee8c3957e68cdb3f91bdc483f0ed05a0da26eca3be4c566d087d90dc2ca293be23b2a9de0bcafc1c", "latest"]
