openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/miscellaneous/sha3:
    post:
      operationId: sha3
      summary: "[Miscellaneous] klay_sha3"
      description: |
        Returns Keccak-256 (not the standardized SHA3-256) of the given data.

        **JSONRPC:** `klay_sha3`

      tags:
        - klay

      parameters:
        - name: data
          required: true
          schema:
            type: string
            format: DATA
          description: The data to convert into a SHA3 hash.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlaySha3Req"

      responses:
        200:
          description: Return the SHA3 result of the given data.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlaySha3Resp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/miscellaneous/sha3.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/miscellaneous/KlaySha3Example.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/miscellaneous/sha3.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/miscellaneous/sha3.py"

components:
  schemas:
    KlaySha3Req:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_sha3'
        params:
          type: array
          items:
            title: data
            type: string
            format: DATA
          description: The data to convert into a SHA3 hash.
          example:  ["0x11223344"]

    KlaySha3Resp:
        type: object
        properties:
          result:
            type: string
            format: 32-byte DATA
            example: "0x36712aa4d0dd2f64a9ae6ac09555133a157c74ddf7c079a70c33e8b4bf70dd73"
            description: The SHA3 result of the given data.
