name: "SDK publish on release"

on:
  workflow_run:
    workflows: ["testing"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        id: last_successful_commit_pr
        with:
            main-branch-name: "main"
            workflow-id: "publish.yml"
            last-successful-event: "pull-request"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: generate code and namespace
        shell: bash
        run: |
          cd web3rpc/codegen && gradle wrapper && gradle wrapper clean :deployJar && cd - &&\
          cd web3rpc/rpc-specs && npm install && bash -x generate-namespace.sh && cd 

      - name: Verify Changed files
        uses: tj-actions/changed-files@v46
        id: verify-changed-files
        with:
          base_sha: ${{ steps.last_successful_commit_pr.outputs.base }}
          files_yaml: | 
            ethers-ext:  
              - "ethers-ext/package.json"
            web3js-ext:  
              - "web3js-ext/package.json"
            viem-ext:  
              - "viem-ext/package.json"
            web3j-ext:
              - "web3j-ext/web3j-ext/build.gradle"
            web3py-ext:
              - "web3py-ext/setup.py"
            web3rpc:
              - "web3rpc/sdk/client/java/java-config.yaml"
              - "web3rpc/sdk/client/javascript/javascript-config.yaml"
            js-ext-core: 
              - "js-ext-core/package.json"

      - name: Publish web3j-ext
        if: steps.verify-changed-files.outputs.web3j-ext_any_changed == 'true'
        shell: bash
        run: |
          cd web3j-ext/web3j-ext && gradle wrapper && gradle build && gradle publish \
          && cd build/libs && zip -r web3j-ext.zip io \
          && curl POST --verbose --header "Authorization: Bearer $PUBLISHER_TOKEN" --form bundle=@web3j-ext.zip https://central.sonatype.com/api/v1/publisher/upload
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          PUBLISH_TO_MAVEN_PUBLIC: true
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}

      - name: generate ethers-ext sdk
        if: steps.verify-changed-files.outputs.ethers-ext_any_changed == 'true' 
        shell: bash
        run: |
          cd ethers-ext && npm install && npm run build && cd -

      - name: publish ethers-ext sdk
        if: steps.verify-changed-files.outputs.ethers-ext_any_changed == 'true' 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ethers-ext && npx pnpm --filter "@kaiachain/*" -r publish --publish-branch main --no-git-check --access=public && cd -

      - name: generate web3js-ext 
        if: steps.verify-changed-files.outputs.web3js-ext_any_changed == 'true' 
        shell: bash
        run: |
          cd web3js-ext && npm install && npm run build && cd -

      - name: publish web3js-ext
        if: steps.verify-changed-files.outputs.web3js-ext_any_changed == 'true' 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd web3js-ext && npx pnpm --filter "@kaiachain/*" -r publish --publish-branch main --no-git-check --access=public && cd -

      - name: generate viem-ext 
        if: steps.verify-changed-files.outputs.viem-ext_any_changed == 'true' 
        shell: bash
        run: |
          cd viem-ext && npm install && npm run build && cd -

      - name: publish viem-ext
        if: steps.verify-changed-files.outputs.viem-ext_any_changed == 'true' 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd viem-ext && npx pnpm --filter "@kaiachain/*" -r publish --publish-branch main --no-git-check --access=public && cd -

      - name: generate web3rpc-python 
        if: steps.verify-changed-files.outputs.web3py-ext_any_changed == 'true'
        shell: bash
        run: |
          cd web3rpc/sdk/client/python && bash -x python-generate.sh && cd -

      - name: generate web3py-ext sdk
        if: steps.verify-changed-files.outputs.web3py-ext_any_changed == 'true'     
        shell: bash
        run: |
          cd web3py-ext &&\
          python -m pip install build wheel twine &&\
          ls -ls &&\
          python setup.py bdist_wheel &&\
          cd -

      - name: Publish web3py-ext sdk
        if: steps.verify-changed-files.outputs.web3py-ext_any_changed == 'true'     
        uses: pypa/gh-action-pypi-publish@release/v1
        continue-on-error: true
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: web3py-ext/dist

      - name: generate web3rpc-java sdk
        if: steps.verify-changed-files.outputs.web3rpc_any_changed  == 'true' 
        shell: bash
        run: |
          cd web3rpc/sdk/client/java && bash -x java-generate.sh  && cd -
        env:
          PUBLISH_TO_MAVEN_PUBLIC: true
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}

      - name: Publish web3rpc-java sdk
        if: steps.verify-changed-files.outputs.web3rpc_any_changed   == 'true'
        run: |
          cd web3rpc/sdk/client/java/openapi && gradle build && gradle publish \
          && cd build/libs && zip -r web3rpc-java.zip io \
          && curl POST --verbose --header "Authorization: Bearer $PUBLISHER_TOKEN" --form bundle=@web3rpc-java.zip https://central.sonatype.com/api/v1/publisher/upload
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          PUBLISH_TO_MAVEN_PUBLIC: true
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          ORG_GRADLE_PROJECT_SIGNINGKEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
            
      - name: generate web3rpc-javascript sdk
        if: steps.verify-changed-files.outputs.web3rpc_any_changed == 'true' 
        shell: bash
        run: |
          cd web3rpc/sdk/client/javascript && bash -x javascript-generate.sh && cd -

      - name: publish web3rpc-javascript sdk
        if: steps.verify-changed-files.outputs.web3rpc_any_changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd web3rpc/sdk/client/javascript/openapi && npx pnpm --filter "@kaiachain/*" -r publish --publish-branch main --no-git-check --access=public && cd -

      - name: generate js-ext-core sdk
        if: steps.verify-changed-files.outputs.js-ext-core_any_changed == 'true' 
        shell: bash
        run: |
          cd js-ext-core && npm install && npm run build && cd -

      - name: publish js-ext-core sdk
        if: steps.verify-changed-files.outputs.js-ext-core_any_changed == 'true' 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd js-ext-core && npx pnpm --filter "@kaiachain/*" -r publish --publish-branch main --no-git-check --access=public && cd -

