openapi: "3.0.2"
info:
  title: KAIA OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/block/getHeaderByNumber:
    post:
      operationId: getHeaderByNumber
      summary: "[Block] klay_getHeaderByNumber"
      description: |
        Returns information about a header by number. This API works only on RPC call, not on JavaScript console.

        **NOTE:** *This API is supported from Kaia v1.7.0.*

        **JSONRPC:** `klay_getHeaderByNumber`
      tags:
        - klay

      parameters:
        - name: blockNumberOrTag
          in: query
          description: Integer or hexadecimal block number, or the string "earliest", "latest" or "pending" as in the default block parameter.
          required: true
          schema:
            $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayGetHeaderByNumberReq"

      responses:
        200:
          description: Returns information about a header by number
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayGetHeaderByNumberResp"

      x-codeSamples:
        - lang: "Shell"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/block/getHeaderByNumber.sh"
        - lang: "Java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/klay/block/KlayGetHeaderByNumberExample.java"
        - lang: "JavaScript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/block/getHeaderByNumber.js"
        - lang: "Python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/klay/block/getHeaderByNumber.py"

components:
  schemas:
    KlayGetHeaderByNumberReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_getHeaderByNumber'
        params:
          type: array
          items:
            properties:
              BlockNumberOrTag:
                $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/BlockNumberOrTag"
          example:  ["0x1b4"]

    KlayGetHeaderByNumberResp:
      type: object
      properties:
        result:
          $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/KlayHeaderObject"

